### ISSUE TITLE
Supplemental files imported separately.

### ISSUE THREAD

**Issue by amiles4** [emory-libraries/etd-issues#11]
Restarting this 3.14.2018: I received an extra notification following submission indicating that the video file I attached to the record was imported later. Are supplemental files being imported separately from the initial submission? Does this have anything to do with the inability to see the supplemental thumbnails after submission?
![image002.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46e1999b2487d3f9ddabf301b44fff9e2c4533317346f62a22ddb77ce7167d045d5c4bab41585e16fcf1817ff0b32e6c981e5ab38532022d8c6853beb2901dbf0bbb258a4d83b0bf8f4ec9ec3e22f5c6.png)

**Comment by amiles4** [comment]
I have not been able to recreate this problem exactly (meaning I have not been able to get the File Import notification again). However, we have noticed that multiple supplemental files requires refreshing the page multiple times in order to have all the thumbnails/files appear on the record.

**Comment by amiles4** [comment]
![Screen Shot 2018-01-16 at 1.46.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f56b7191a379f1162d4f5a585ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74de04f5da1113467ee762431.png)
![Screen Shot 2018-01-16 at 1.47.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f56b7191a379f1162c4f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74de04f5da1113466e1712431.png)

**Comment by amiles4** [comment]
I was able to recreate the File Import notification again by attaching multiple supplemental files, and including one large video file, for which a later notification was sent claiming the file was imported.

**Comment by rotated8** [comment]
@fpici, @amiles4- The title seems to suggest this is no longer an issue. Can this be closed?

**Comment by fpici** [comment]
@rotated8 I plan on asking DCE what this notifications is all about. Let us keep it in backlog until We find out. Okay?

**Comment by rotated8** [comment]
Sounds good!

**Comment by fpici** [comment]
I pinged Bess & Shanita on this 2.6.2018: Hello friends. Anna and I have a question. We notice that whenever we add a large supplemental file via Box — like a movie -- and submit, the creator/depositor ONLY gets an additional notification that alerts the creator/depositor that a file was successfully imported. We figure that this is the proper performance BUT the notification is only visible to the creator/depositor and not visible to Anna nor me as Superusers. Since we may need to see such actions to confirm successful imports of large files, how hard would it be for us to also see those Successful import notifications?

**Comment by shanitajohn** [comment]
Thanks, Fran! I'm going to let Bess remain heads down on ProQuest for the moment, but we are going to follow-up on this question, I'll track it in our hosting meeting, too.

**Comment by fpici** [comment]
Shanita.

Not a problem at all. This is very low priority and something that we can certainly mitigate if we need to.
So heads down for Bess ☺
Venture forth with Proquest work …




Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html

**Comment by fpici** [comment]
Prioritizing this  because Anna and I have noticed this is an issue with all Box uploads, not just large files. What we see in our testing is that when a depositor uploads from box, the system (intermittently) throws an error when the depositor hits submit to complete their deposit. This occurs in staging and in production.  Anna and I are assuming that the file import from Box is not starting until after the depositor has Reviewed and Submitted, which is why it throws the error. (see screenshot)
![Screen Shot 2018-03-14 at 8.54.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f76b7191a370f1172f4f5b595edd3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19141c95df44ae14e57a51b3e63e4772431.png)

**Comment by fpici** [comment]
![ETDError.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46cda0be069091a69dabf301b44fff9e2c4533317346f62a22ddb77ce7167d045d5c4bab41585e16fcf1817ff0b32e6c981e5ab38532022d8c6853beb2901dbd0bbb25894e85b5be8e44c7ef3524f5c6.png)

**Comment by fpici** [comment]
@rotated8 I restarted this ticket and made it a priority. I cannot remove the first comment that says CANCEL, even though the body of the comment says Restart ?? but it is the most important one right now. :-)

**Comment by amiles4** [comment]
@rotated8 says: the files are being processed in the background

@rosy1280 suggests: that notifications or language that says the files are being processed in the background, come back.

@rotated8 says: there may not be a way to do this because we don't know what the appropriate amount of time to keep around the message is.

**Comment by amiles4** [comment]
@fpici and @amiles4 will keep an eye on this and we'll revisit in the fall.
