### ISSUE TITLE
School Approvers cannot see the student's Post Graduation email address.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#34]
As a School Approver/ADAP, I want to be able to see the Student/Alum's non-Emory email address, so I can contact them after their Emory email address is disable.

**Comment by fpici** [comment]
This function was available in legacy ETDs. See screenshot of the view that FrAnna and I have as SuperUsers.
The ADAPS, and Approvers want to see the student's Post-Graduation email that is nested in an expansion of the submitted record.
![Screen Shot 2018-04-12 at 2.33.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f16b7191a37af111284f5d565ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df448e4485ca713356be7712431.png)

**Comment by mark-dce** [comment]
FWIW - the e-mail address is not currently displayed on the show view since that's a publicly accessible view.  It could be displayed only to administrators and approvers with some amount of extra development.

The edit view is restricted however, and an approver or administrator should be able to see the e-mail by clicking on edit and viewing the e-mail via the edit form (just don't save any changes...)

**Comment by fpici** [comment]
I just tested this on Jen Doty's login who is set as a Candler Approver in QA. I do not have an Edit view when I try Mark's suggestion above. Here is a sample record: https://qa-etd.library.emory.edu/concern/etds/j6731463c

**Comment by fpici** [comment]
Looks good now, I see the post-Emory email. Many thanks!!
