### ISSUE TITLE
Students still cannot upload from Box (see full description below)

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#37]
Students cannot upload from Box. We had another summer submission where the student received a "Something Went wrong" error when depositing their file from their Box account. Although DCE has made several attempts to resolve in these below tickets, it is still a problem.  Here are the past tickets: Freshdesk Tix #42, 46, 47, 51, 52, 53 and Waffle Laevigata tix #919, 925, 960, 961, 984. For now, until the Box feature upload is tested and resolved, we suggest that we remove the Box upload option from the UI on the My PDF and Supplemental Files Tab pages, and replace with a message that says "For PDFs 100MB or larger, please contact the ETD team using the Help Form located here: http://sco.library.emory.edu/etds/help-form.html."

**Comment by fpici** [comment]
6.13.2018: For now, until the Box feature upload is tested and resolved, we suggest that we remove the Box upload option from the UI and replace with a message that says "For PDFs 100MB or larger, please contact the ETD team using the Help Form located here: http://sco.library.emory.edu/etds/help-form.html." Perhaps larger than 25 MB locally"

**Comment by amiles4** [comment]
@rosy1280 suggests: lets keep track of more information about what is happening with box and pass along to DCE so they can check the logs to see what is going on.  the original problem that was reported is no longer cropping up in the logs.

**Comment by rosy1280** [comment]
Some questions that we might want to ask for help with troubleshooting:
- [ ] has the user used emory's box service before?
- [ ] was the user able to successfully upload content to box
- [ ] if the user is using box sync (i.e. the feature where files on your computer also magically appear in box), has the file finished syncing between your computer and box?

Some things to record when users run into problems:
- [ ] what is the users netid
- [ ] when did the user experience the problem (date and a round about time)
- [ ] how many attempts did the user make

**Comment by amiles4** [comment]
ETD Help Form submitted 6/22/18 at 4:47 a.m.
Full Name: Jiayun Elvin Ong
Email: elvin.ong@emory.edu
Subject: Unable to submit ETD = Error message upon submission
Message: After entering all my details through the various tabs, I click "Submit" on the final tab. Instead of getting any confirmation of submission, all I see on the next page is "The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. If you are the application owner check the logs for more information." I have tried submitting at least four times over 2 days using 2 different browsers and I still get the same error message. Please help.

Contacted student 6/22/18 at 8 a.m.
Asked them to try submitting locally and to send screenshots of their preview page if submitting locally did not work.

Student replied 6/22/18 at 10:38 p.m.
Successful submission https://etd.library.emory.edu/concern/etds/gm80hv44c
Dear Anna,
 
Thank you very much for your helpful instructions. I’ve followed them and have managed to successfully upload the dissertation. It is now under initial review. I believe the problem must be uploading through Box. In any case, thanks again.
 
Best regards,
Elvin

**Comment by fpici** [comment]
Ho Collin. An ETD Help form submitted today  7.23.2018 at 12:56PM. Student SONIA J LAURIE (sonia.laurie@emory.edu) tried uploading from Box and received the following error: "The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. If you are the application owner check the logs for more information." 

Anna suggested that she try to upload from her local machine and it worked fine.

Just keeping you in the loop for troubleshooting tips :-)

**Comment by rotated8** [comment]
This ticket will need more monitoring through winter submission season, as the new upload from (which does not encourage Box use) has not been tested.
