### ISSUE TITLE
Cannot reinstate embargo on an expired migrated legacy ETD restriction 

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#53]
**Please replace the things in italics (_like this_).**

I believe there is a problem with _setting embargoes on the Manage Embargoes Tab and on the Permissions at the record's file level_, because when _I, as a Superuser_ does the following: Search for the record in the Manage Embargoes tab, I cannot find the record because the embargo has expired. I also cannot reinstate the embargo on the file's Permission level and save any changes successfully.

_Steps to reproduce the behavior, like_

_1. Log in_as a Superuser
_2. Click on '....'_ Manage Embargoes tab. Search for record by Title. No results found.
_3. Scroll down to '....' The actual record located here: https://etd.library.emory.edu/concern/etds/hx11xf69w?locale=en; go to the Record's file level. Click on Permissions level, change the embargo date to 2020-09-05 to reinstate the expired embargo and save. 
_4. See error_ N/A

I expected the new embargo date of 2020-09-05 to be in place and the files to change to restricted status.

_something to happen_ But the embargo date did not change.

but instead

_something else happened_. The record remains in Open Access and the embargo date stayed at 2018.

Here is a link to the migrated record in the New ETDS: https://etd.library.emory.edu/concern/etds/hx11xf69w?locale=en

I believe this affects _any record with an embargo date that needs to be reinstated_a reason_, and they are _a qualifier_ impacted because _another reason_.

**Comment by rotated8** [comment]
I believe there is a problem with _setting embargoes on the Manage Embargoes Tab and on the Permissions at the record's file level_, because when _a superuser_ does the following:

1. Log in as a superuser
1. Click on Manage Embargoes tab. 
1. Search for record by Title. (No results found. ETD exists at https://etd.library.emory.edu/concern/etds/hx11xf69w)
1. Go to the Record's file level.
1. Click on Permissions level,  and change the embargo date to 2020-09-05 to reinstate the expired embargo and save. 

I expected 

_the new embargo date of 2020-09-05 to be in place and the files to change to restricted status._

but instead

_The record remains in Open Access and the embargo date stayed at 2018._

I believe this affects _maybe a dozen_ of our users because _we don't have many ETDs that need to have embargoes reinstated_, and they are _highly_ impacted because _they expect their ETDs to remain embargoed_.

**Comment by fpici** [comment]
Bess commented  9.6.2018: @rotated8 and I talked about this and it's not a feature we're currently able to support. We think the requests for this will be few enough that for now they'll come in as freshdesk tickets and someone can fix it on the command line.

I'm leaving this ticket in the back log and marking it as future scope, so we remember that this is a desired feature. Ticket 1795: https://github.com/curationexperts/laevigata/issues/1795

**Comment by fpici** [comment]
We have two Legacy ETD records that need to have the embargo reinstated and extended. I am putting the information here for Collin to create a Freshdesk ticket for this work as Bess suggested on 9.6.2018.

Author: Emily Moore
Title: "Strange Histories": A Cultural History of the Legend of Lost Confederate Gold in Washington, Georgia
Pid: https://etd.library.emory.edu/concern/etds/hx11xf69w?locale=en 
Embargo TWO more years.
====
Author:
Title: "Cross-Strait Relations: An Application of Liberal Peace Theory"
Pid: https://etd.library.emory.edu/concern/etds/ks65hc85n?locale=en
Embargo: THREE more years

Many thanks in advance.

**Comment by fpici** [comment]
We have two Legacy ETD records that need to have the embargo reinstated and extended. I am putting the information here for Collin to create a Freshdesk ticket for this work as Bess suggested on 9.6.2018.

Author: Emily Moore
Title: "Strange Histories": A Cultural History of the Legend of Lost Confederate Gold in Washington, Georgia
Pid: https://etd.library.emory.edu/concern/etds/hx11xf69w?locale=en 
Embargo TWO more years.
====
Author: Woolheater, Ashley Lynette
Title: "Cross-Strait Relations: An Application of Liberal Peace Theory"
Pid: https://etd.library.emory.edu/concern/etds/ks65hc85n?locale=en
Embargo: THREE more years

Many thanks in advance.

**Comment by rotated8** [comment]
Submitted to Freshdesk
